set(ASSIMP_ROOT ${LIB_DIR}/assimp)

set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT FALSE CACHE BOOL "ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT" FORCE)
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT FALSE CACHE BOOL "ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT" FORCE)
set(ASSIMP_BUILD_OBJ_IMPORTER TRUE CACHE BOOL "ASSIMP_BUILD_OBJ_IMPORTER" FORCE)
set(BUILD_SHARED_LIBS TRUE CACHE BOOL "BUILD_SHARED_LIBS" FORCE)
set(ASSIMP_NO_EXPORT TRUE CACHE BOOL "ASSIMP_NO_EXPORT" FORCE)
set(ASSIMP_INSTALL FALSE CACHE BOOL "ASSIMP_INSTALL" FORCE)
set(ASSIMP_BUILD_ASSIMP_TOOLS FALSE CACHE BOOL "ASSIMP_BUILD_ASSIMP_TOOLS" FORCE)
set(ASSIMP_BUILD_SAMPLES FALSE CACHE BOOL "ASSIMP_BUILD_SAMPLES" FORCE)
set(ASSIMP_BUILD_TESTS FALSE CACHE BOOL "ASSIMP_BUILD_TESTS" FORCE)

add_subdirectory(${ASSIMP_ROOT})
include_directories(${ASSIMP_ROOT}/include)